package core.SymbolicExecution.AstNode.Expression.Type;

import org.eclipse.jdt.core.dom.QualifiedType;
import org.eclipse.jdt.core.dom.SimpleName;
import org.eclipse.jdt.core.dom.Type;

/**
 * Type node for an AST-level qualified type: {@code qualifier.SimpleName}.
 *
 * <p>A {@link QualifiedType} is generated by JDT when a reference type is written
 * as an explicit dot-separated qualifier followed by a simple name, for example:
 * <pre>{@code
 *   Outer.Inner field;          // qualifier=Outer, name=Inner
 *   p.q.Outer.Inner field;      // qualifier=p.q.Outer, name=Inner
 * }</pre>
 *
 * <p>This differs from {@link SimpleTypeNode} (which wraps a single name that
 * may happen to contain dots) and from {@link NameQualifiedTypeNode} (AST level
 * 8+ form that attaches annotations to the qualifier).
 */
public class QualifiedTypeNode extends TypeNode {

    private final QualifiedType jdtType;

    /** Lazily computed TypeNode wrapping the qualifier portion. */
    private TypeNode qualifierNode;

    // -------------------------------------------------------------------------
    // Constructor (private – use from())
    // -------------------------------------------------------------------------

    private QualifiedTypeNode(QualifiedType jdtType) {
        this.jdtType = jdtType;
    }

    // -------------------------------------------------------------------------
    // Static factory
    // -------------------------------------------------------------------------

    /**
     * Wraps a JDT {@link QualifiedType} node.
     *
     * @param type the JDT qualified-type node
     * @return a new {@link QualifiedTypeNode}
     */
    public static QualifiedTypeNode from(QualifiedType type) {
        if (type == null) throw new IllegalArgumentException("QualifiedType must not be null");
        return new QualifiedTypeNode(type);
    }

    // -------------------------------------------------------------------------
    // API
    // -------------------------------------------------------------------------

    /**
     * Returns the qualifier as a {@link TypeNode} (recursively wrapping the
     * left-hand side of the dot).
     */
    public TypeNode getQualifier() {
        if (qualifierNode == null) {
            qualifierNode = TypeNode.from(jdtType.getQualifier());
        }
        return qualifierNode;
    }

    /**
     * Returns the simple name on the right-hand side of the qualifying dot
     * (e.g. {@code Inner} for {@code Outer.Inner}).
     */
    public SimpleName getSimpleName() {
        return jdtType.getName();
    }

    /**
     * Returns a human-readable qualified name by combining qualifier and simple name.
     * Note: this walks up through nested qualifiers, so it reconstructs the full
     * dot-separated string as written in the source.
     */
    public String getFullyQualifiedName() {
        return jdtType.getQualifier().toString() + "." + jdtType.getName().getIdentifier();
    }

    // -------------------------------------------------------------------------
    // TypeNode contract
    // -------------------------------------------------------------------------

    @Override
    public Type getJdtType() {
        return jdtType;
    }

    // -------------------------------------------------------------------------
    // Object
    // -------------------------------------------------------------------------

    @Override
    public String toString() {
        return "QualifiedTypeNode{" + getFullyQualifiedName() + "}";
    }
}